Repository COS301-SE-2021/Escape-Room-Planner, pull requests merged in 2021-06, with the labels that each got.

#24 Feature/next vertex dev READ DESCRPTION
  .travis.yml
  app/Services/room_services.rb
  app/models/vertex.rb
  db/migrate/20210607153557_change_next_v_to_be_bigint_in_vertices.rb
  db/migrate/20210607160419_create_vertices_vertices_join_table.rb
  db/migrate/20210607165010_delete_next_v_column_from_vertices.rb
  db/schema.rb
  test/fixtures/vertex_edges.yml
  test/fixtures/vertices.yml
  test/models/vertex_test.rb
Labels: enhancement, feature

#25 Feature/next vertex dev
  app/Services/create_escaperoom_request.rb
  app/Services/create_puzzle_request.rb
  app/Services/room_services.rb
  test/unit/puzzle_test.rb
Labels: enhancement

#36 Clue: Fixed Unit Test
  app/Services/create_clue_request.rb
  app/Services/create_clue_response.rb
  app/Services/room_services.rb
  config/database.yml
  test/unit/clue_test.rb
Labels: fix

#38 API calls added
  app/controllers/api/v1/vertex_controller.rb
Labels: enhancement

#44 Feature/update to vertex
  app/models/vertex.rb
  test/models/vertex_test.rb
  test/unit/clue_test.rb
  test/unit/container_test.rb
  test/unit/create_key_test.rb
  test/unit/puzzle_test.rb
Labels: fix

#48 Feature/reset room
  app/Services/reset_escape_room_request.rb
  app/Services/reset_escape_room_response.rb
  app/Services/room_services.rb
  test/unit/er_test.rb
Labels: feature

#59 Feature/update vertex
  .travis.yml
  app/Services/room_services.rb
  app/Services/update_vertex_request.rb
  app/Services/update_vertex_response.rb
  test/unit/er_test.rb
Labels: feature
