Repository COS301-SE-2021/Escape-Room-Planner, pull requests merged in 2021-08, with the labels that each got.

#79 fixed code smells
  Backend/Backend.iml
  Backend/app/Services/create_clue_request.rb
  Backend/app/Services/create_container_request.rb
  Backend/app/Services/create_container_response.rb
  Backend/app/Services/create_escaperoom_request.rb
  Backend/app/Services/create_escaperoom_response.rb
  Backend/app/Services/create_key_request.rb
  Backend/app/Services/create_puzzle_request.rb
  Backend/app/Services/remove_vertex_request.rb
  Backend/app/Services/room_services.rb
  Backend/app/Services/update_vertex_request.rb
  Backend/app/controllers/api/v1/room_controller.rb
  Backend/app/controllers/api/v1/vertex_controller.rb
  Backend/app/models/vertex.rb
  Backend/app/views/layouts/application.html.erb
  Backend/app/views/layouts/mailer.html.erb
  Backend/config/application.rb
  Backend/config/database.yml
  Backend/config/initializers/cors.rb
  Backend/public/404.html
  Backend/public/422.html
  Backend/public/500.html
  Backend/test/test_helper.rb
  Backend/test/unit/clue_test.rb
  Backend/test/unit/container_test.rb
  Backend/test/unit/create_key_test.rb
  Backend/test/unit/er_test.rb
  Backend/test/unit/puzzle_test.rb
  Frontend/angular.json
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/app/models/clue.model.ts
  Frontend/src/app/models/container.model.ts
  Frontend/src/app/models/key.model.ts
  Frontend/src/app/models/puzzle.model.ts
  Frontend/src/app/models/vertex.model.spec.ts
  Frontend/src/app/models/vertex.model.ts
  Frontend/src/app/pages/room-creator/room-creator.component.css
  Frontend/src/app/pages/room-creator/room-creator.component.html
  Frontend/src/app/pages/room-creator/room-creator.component.ts
  Frontend/src/app/services/vertex.service.ts
  Frontend/src/index.html
Labels: help wanted

#86 Feature/connect vertex
  Backend/app/Services/connect_vertices_request.rb
  Backend/app/Services/connect_vertices_response.rb
  Backend/app/Services/room_services.rb
  Backend/app/controllers/api/v1/vertex_controller.rb
  Backend/test/controllers/vertex_controller_test.rb
  Backend/test/unit/er_test.rb
  Frontend/src/app/pages/room-creator/room-creator.component.ts
Labels: feature

#91 Feature/connect vertex
  Backend/app/controllers/api/v1/room_controller.rb
  Backend/app/controllers/api/v1/vertex_controller.rb
  Backend/app/models/escape_room.rb
  Backend/test/controllers/room_controller_test.rb
  Backend/test/controllers/vertex_controller_test.rb
  Backend/test/fixtures/escape_rooms.yml
  Backend/test/fixtures/vertices.yml
  Frontend/src/app/directives/draggable.directive.spec.ts
  Frontend/src/app/directives/droppable.directive.spec.ts
  Frontend/src/app/models/clue.model.spec.ts
  Frontend/src/app/models/container.model.spec.ts
  Frontend/src/app/models/key.model.spec.ts
  Frontend/src/app/models/puzzle.model.spec.ts
  Frontend/src/app/models/vertex.model.ts
  Frontend/src/app/pages/room-creator/room-creator.component.css
  Frontend/src/app/pages/room-creator/room-creator.component.html
  Frontend/src/app/pages/room-creator/room-creator.component.ts
  Frontend/src/app/services/vertex.service.spec.ts
  Frontend/src/app/services/vertex.service.ts
  Frontend/src/assets/svg/trash-fill.svg
  Frontend/src/index.html
Labels: enhancement
